version : '3.9'

service:

  postgres:
    container_name: postgres_project
    image: postgres
    environment: 
      - POSTGRES_DB=shop_book
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=jl2693
    ports: 
      - "5432:5432"
    networks:
      - main
    restart: on-failure
    volumes: 
      - postgres_data:/var/lib/postgresql/data  
  
  app:
    container_name: app
    build: .
    command: sh -c "python manage.py migrate && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/project
      - ./static:/app/static
      - ./media:/app/media
        
    depends_on:
      - postgres_project
    expose:
      - "8000"
    networks:
      - main  
    restart: on-failure
  

  nginx:
    container_name: nginx
    command: nginx -g 'deamon off;'
    depends_on:
      -shop_book
    image: nginx
    ports: 
      - "80:80"
    restart: on_failure
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./static:/app/static
      - ./media:/app/media


networks:
  main:

volumes: 
  postgres_data:
