# Generated by Django 3.1.7 on 2021-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210305_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gener',
            field=models.ManyToManyField(null=True, to='book.Gener'),
        ),
    ]
