# Generated by Django 3.1.7 on 2021-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210305_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gener',
            field=models.ManyToManyField(to='book.Gener'),
        ),
    ]
